name: CI workflow

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest # github runner
        steps:
            - name: checkout code
              uses: actions/checkout@v4 # clone the code into a ubuntu runner

            - name: setup docker build
              uses: docker/setup-buildx-action@v4